project:
  type: website

website:
  title: "Min Min Soh"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/etc5523-2022
format:
  html:
    theme: lumen
    font-family: futura-lt-w01-book,sans-serif;
    css: styles.css



